"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const departmentController_1 = require("../controllers/departmentController");
// import { authenticate, checkUserRights } from "../middleware/authMiddleware";
const router = (0, express_1.Router)();
router.get("/", departmentController_1.getAllDepartmentsHandler);
router.post("/", departmentController_1.createDepartmentHandler);
router.get("/:id", departmentController_1.getSingleDepartmentHandler);
router.put("/", departmentController_1.updateDepartmentHandler);
exports.default = router;
